// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhE9L4A56Wjy-7OEZk-j61phSYqm8aVqg',
    appId: '1:198230389564:web:d04bb8173597a71e536439',
    messagingSenderId: '198230389564',
    projectId: 'bluh-park',
    authDomain: 'bluh-park.firebaseapp.com',
    storageBucket: 'bluh-park.appspot.com',
    measurementId: 'G-N07YH1V53L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAVJYv2arw46-yEBR_Mk_aSFsUdnO47p0',
    appId: '1:198230389564:android:77e1cb3032632283536439',
    messagingSenderId: '198230389564',
    projectId: 'bluh-park',
    storageBucket: 'bluh-park.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxrvX4UrbNQQFjTseKdcG2NjMMxEUR7F0',
    appId: '1:198230389564:ios:b75a033eb2f07a48536439',
    messagingSenderId: '198230389564',
    projectId: 'bluh-park',
    storageBucket: 'bluh-park.appspot.com',
    iosClientId: '198230389564-4h91truusjrkcnbu9u1dijiv0oufnbol.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluehpark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxrvX4UrbNQQFjTseKdcG2NjMMxEUR7F0',
    appId: '1:198230389564:ios:810ee7d3258bbe32536439',
    messagingSenderId: '198230389564',
    projectId: 'bluh-park',
    storageBucket: 'bluh-park.appspot.com',
    iosClientId: '198230389564-cn12pet1r156jhd3sarfa9sgjanptvuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluehpark.RunnerTests',
  );
}
